use serde::Serialize;
use std::str::FromStr;

#[derive(Debug, Serialize, PartialEq)]
#[non_exhaustive]
pub enum Category {
    // Main categories
    // https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry
    AudioVideo,
    Audio,
    Video,
    Development,
    Education,
    Game,
    Graphics,
    Network,
    Office,
    Science,
    Settings,
    System,
    Utility,
    // Additional categories
    // https://specifications.freedesktop.org/menu-spec/latest/apas02.html
    Building,
    Debugger,
    IDE,
    GUIDesigner,
    Profiling,
    RevisionControl,
    Translation,
    Calendar,
    ContactManagement,
    Database,
    Dictionnary,
    Chart,
    Email,
    Finance,
    FlowChart,
    PDA,
    ProjectManagement,
    Presentation,
    Spreadsheet,
    WordProcessor,
    TwoDGraphics,
    VectorGraphics,
    RasterGraphics,
    ThreeDGraphics,
    Scanning,
    OCR,
    Photography,
    Publishing,
    Viewer,
    TextTools,
    DesktopSettings,
    HardwareSettings,
    Printing,
    PackageManager,
    Dialup,
    InstantMessaging,
    Chat,
    IRCClient,
    Feed,
    HamRadio,
    News,
    P2P,
    RemoteAccess,
    Telephony,
    TelephonyTools,
    VideoConference,
    WebBrowser,
    WebDevelopment,
    Midi,
    Mixer,
    Sequencer,
    Tuner,
    TV,
    AudioVideoEditing,
    Player,
    Recorder,
    DiscBurning,
    ActionGame,
    AdventureGame,
    ArcadeGame,
    BoardGame,
    BlocksGame,
    CardGame,
    KidsGame,
    LogicGame,
    RolePlaying,
    Shooter,
    Simulation,
    SportsGame,
    StrategyGame,
    Art,
    Construction,
    Music,
    Languages,
    ArtificialIntelligence,
    Astronomy,
    Biology,
    Chemistry,
    ComputerScience,
    DataVisualization,
    Economy,
    Electricity,
    Geography,
    Geology,
    Geoscience,
    History,
    Humanities,
    ImageProcessing,
    Literature,
    Maps,
    Math,
    NumericalAnalysis,
    MedicalSoftware,
    Physics,
    Robotics,
    Spirituality,
    Sports,
    ParallelComputing,
    Amusement,
    Archiving,
    Compression,
    Electronics,
    Emulator,
    Engineering,
    FileTools,
    FileManager,
    TerminalEmulator,
    Filesystem,
    Monitor,
    Security,
    Accessibility,
    Calculator,
    Clock,
    TextEditor,
    Documentation,
    Adult,
    Core,
    KDE,
    GNOME,
    XFCE,
    GTK,
    Qt,
    Motif,
    Java,
    ConsoleOnly,
    // Reserved categories
    // https://specifications.freedesktop.org/menu-spec/latest/apas03.html
    Screensaver,
    TrayIcon,
    Applet,
    Shell,
    Unknown,
}

impl FromStr for Category {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let c = match value {
            "AudioVideo" => Category::AudioVideo,
            "Audio" => Category::Audio,
            "Video" => Category::Video,
            "Development" => Category::Development,
            "Education" => Category::Education,
            "Game" => Category::Game,
            "Graphics" => Category::Graphics,
            "Network" => Category::Network,
            "Office" => Category::Office,
            "Science" => Category::Science,
            "Settings" => Category::Settings,
            "System" => Category::System,
            "Utility" => Category::Utility,
            "Building" => Category::Building,
            "Debugger" => Category::Debugger,
            "IDE" => Category::IDE,
            "GUIDesigner" => Category::GUIDesigner,
            "Profiling" => Category::Profiling,
            "RevisionControl" => Category::RevisionControl,
            "Translation" => Category::Translation,
            "Calendar" => Category::Calendar,
            "ContactManagement" => Category::ContactManagement,
            "Database" => Category::Database,
            "Dictionnary" => Category::Dictionnary,
            "Chart" => Category::Chart,
            "Email" => Category::Email,
            "Finance" => Category::Finance,
            "FlowChart" => Category::FlowChart,
            "PDA" => Category::PDA,
            "ProjectManagement" => Category::ProjectManagement,
            "Presentation" => Category::Presentation,
            "Spreadsheet" => Category::Spreadsheet,
            "WordProcessor" => Category::WordProcessor,
            "TwoDGraphics" => Category::TwoDGraphics,
            "VectorGraphics" => Category::VectorGraphics,
            "RasterGraphics" => Category::RasterGraphics,
            "ThreeDGraphics" => Category::ThreeDGraphics,
            "Scanning" => Category::Scanning,
            "OCR" => Category::OCR,
            "Photography" => Category::Photography,
            "Publishing" => Category::Publishing,
            "Viewer" => Category::Viewer,
            "TextTools" => Category::TextTools,
            "DesktopSettings" => Category::DesktopSettings,
            "HardwareSettings" => Category::HardwareSettings,
            "Printing" => Category::Printing,
            "PackageManager" => Category::PackageManager,
            "Dialup" => Category::Dialup,
            "InstantMessaging" => Category::InstantMessaging,
            "Chat" => Category::Chat,
            "IRCClient" => Category::IRCClient,
            "Feed" => Category::Feed,
            "HamRadio" => Category::HamRadio,
            "News" => Category::News,
            "P2P" => Category::P2P,
            "RemoteAccess" => Category::RemoteAccess,
            "Telephony" => Category::Telephony,
            "TelephonyTools" => Category::TelephonyTools,
            "VideoConference" => Category::VideoConference,
            "WebBrowser" => Category::WebBrowser,
            "WebDevelopment" => Category::WebDevelopment,
            "Midi" => Category::Midi,
            "Mixer" => Category::Mixer,
            "Sequencer" => Category::Sequencer,
            "Tuner" => Category::Tuner,
            "TV" => Category::TV,
            "AudioVideoEditing" => Category::AudioVideoEditing,
            "Player" => Category::Player,
            "Recorder" => Category::Recorder,
            "DiscBurning" => Category::DiscBurning,
            "ActionGame" => Category::ActionGame,
            "AdventureGame" => Category::AdventureGame,
            "ArcadeGame" => Category::ArcadeGame,
            "BoardGame" => Category::BoardGame,
            "BlocksGame" => Category::BlocksGame,
            "CardGame" => Category::CardGame,
            "KidsGame" => Category::KidsGame,
            "LogicGame" => Category::LogicGame,
            "RolePlaying" => Category::RolePlaying,
            "Shooter" => Category::Shooter,
            "Simulation" => Category::Simulation,
            "SportsGame" => Category::SportsGame,
            "StrategyGame" => Category::StrategyGame,
            "Art" => Category::Art,
            "Construction" => Category::Construction,
            "Music" => Category::Music,
            "Languages" => Category::Languages,
            "ArtificialIntelligence" => Category::ArtificialIntelligence,
            "Astronomy" => Category::Astronomy,
            "Biology" => Category::Biology,
            "Chemistry" => Category::Chemistry,
            "ComputerScience" => Category::ComputerScience,
            "DataVisualization" => Category::DataVisualization,
            "Economy" => Category::Economy,
            "Electricity" => Category::Electricity,
            "Geography" => Category::Geography,
            "Geology" => Category::Geology,
            "Geoscience" => Category::Geoscience,
            "History" => Category::History,
            "Humanities" => Category::Humanities,
            "ImageProcessing" => Category::ImageProcessing,
            "Literature" => Category::Literature,
            "Maps" => Category::Maps,
            "Math" => Category::Math,
            "NumericalAnalysis" => Category::NumericalAnalysis,
            "MedicalSoftware" => Category::MedicalSoftware,
            "Physics" => Category::Physics,
            "Robotics" => Category::Robotics,
            "Spirituality" => Category::Spirituality,
            "Sports" => Category::Sports,
            "ParallelComputing" => Category::ParallelComputing,
            "Amusement" => Category::Amusement,
            "Archiving" => Category::Archiving,
            "Compression" => Category::Compression,
            "Electronics" => Category::Electronics,
            "Emulator" => Category::Emulator,
            "Engineering" => Category::Engineering,
            "FileTools" => Category::FileTools,
            "FileManager" => Category::FileManager,
            "TerminalEmulator" => Category::TerminalEmulator,
            "Filesystem" => Category::Filesystem,
            "Monitor" => Category::Monitor,
            "Security" => Category::Security,
            "Accessibility" => Category::Accessibility,
            "Calculator" => Category::Calculator,
            "Clock" => Category::Clock,
            "TextEditor" => Category::TextEditor,
            "Documentation" => Category::Documentation,
            "Adult" => Category::Adult,
            "Core" => Category::Core,
            "KDE" => Category::KDE,
            "GNOME" => Category::GNOME,
            "XFCE" => Category::XFCE,
            "GTK" => Category::GTK,
            "Qt" => Category::Qt,
            "Motif" => Category::Motif,
            "Java" => Category::Java,
            "ConsoleOnly" => Category::ConsoleOnly,
            "Screensaver" => Category::Screensaver,
            "TrayIcon" => Category::TrayIcon,
            "Applet" => Category::Applet,
            "Shell" => Category::Shell,
            _ => Category::Unknown,
        };
        Ok(c)
    }
}

impl Into<&'static str> for Category {
    fn into(self) -> &'static str {
        match self {
            Category::AudioVideo => "AudioVideo",
            Category::Audio => "Audio",
            Category::Video => "Video",
            Category::Development => "Development",
            Category::Education => "Education",
            Category::Game => "Game",
            Category::Graphics => "Graphics",
            Category::Network => "Network",
            Category::Office => "Office",
            Category::Science => "Science",
            Category::Settings => "Settings",
            Category::System => "System",
            Category::Utility => "Utility",
            Category::Building => "Building",
            Category::Debugger => "Debugger",
            Category::IDE => "IDE",
            Category::GUIDesigner => "GUIDesigner",
            Category::Profiling => "Profiling",
            Category::RevisionControl => "RevisionControl",
            Category::Translation => "Translation",
            Category::Calendar => "Calendar",
            Category::ContactManagement => "ContactManagement",
            Category::Database => "Database",
            Category::Dictionnary => "Dictionnary",
            Category::Chart => "Chart",
            Category::Email => "Email",
            Category::Finance => "Finance",
            Category::FlowChart => "FlowChart",
            Category::PDA => "PDA",
            Category::ProjectManagement => "ProjectManagement",
            Category::Presentation => "Presentation",
            Category::Spreadsheet => "Spreadsheet",
            Category::WordProcessor => "WordProcessor",
            Category::TwoDGraphics => "TwoDGraphics",
            Category::VectorGraphics => "VectorGraphics",
            Category::RasterGraphics => "RasterGraphics",
            Category::ThreeDGraphics => "ThreeDGraphics",
            Category::Scanning => "Scanning",
            Category::OCR => "OCR",
            Category::Photography => "Photography",
            Category::Publishing => "Publishing",
            Category::Viewer => "Viewer",
            Category::TextTools => "TextTools",
            Category::DesktopSettings => "DesktopSettings",
            Category::HardwareSettings => "HardwareSettings",
            Category::Printing => "Printing",
            Category::PackageManager => "PackageManager",
            Category::Dialup => "Dialup",
            Category::InstantMessaging => "InstantMessaging",
            Category::Chat => "Chat",
            Category::IRCClient => "IRCClient",
            Category::Feed => "Feed",
            Category::HamRadio => "HamRadio",
            Category::News => "News",
            Category::P2P => "P2P",
            Category::RemoteAccess => "RemoteAccess",
            Category::Telephony => "Telephony",
            Category::TelephonyTools => "TelephonyTools",
            Category::VideoConference => "VideoConference",
            Category::WebBrowser => "WebBrowser",
            Category::WebDevelopment => "WebDevelopment",
            Category::Midi => "Midi",
            Category::Mixer => "Mixer",
            Category::Sequencer => "Sequencer",
            Category::Tuner => "Tuner",
            Category::TV => "TV",
            Category::AudioVideoEditing => "AudioVideoEditing",
            Category::Player => "Player",
            Category::Recorder => "Recorder",
            Category::DiscBurning => "DiscBurning",
            Category::ActionGame => "ActionGame",
            Category::AdventureGame => "AdventureGame",
            Category::ArcadeGame => "ArcadeGame",
            Category::BoardGame => "BoardGame",
            Category::BlocksGame => "BlocksGame",
            Category::CardGame => "CardGame",
            Category::KidsGame => "KidsGame",
            Category::LogicGame => "LogicGame",
            Category::RolePlaying => "RolePlaying",
            Category::Shooter => "Shooter",
            Category::Simulation => "Simulation",
            Category::SportsGame => "SportsGame",
            Category::StrategyGame => "StrategyGame",
            Category::Art => "Art",
            Category::Construction => "Construction",
            Category::Music => "Music",
            Category::Languages => "Languages",
            Category::ArtificialIntelligence => "ArtificialIntelligence",
            Category::Astronomy => "Astronomy",
            Category::Biology => "Biology",
            Category::Chemistry => "Chemistry",
            Category::ComputerScience => "ComputerScience",
            Category::DataVisualization => "DataVisualization",
            Category::Economy => "Economy",
            Category::Electricity => "Electricity",
            Category::Geography => "Geography",
            Category::Geology => "Geology",
            Category::Geoscience => "Geoscience",
            Category::History => "History",
            Category::Humanities => "Humanities",
            Category::ImageProcessing => "ImageProcessing",
            Category::Literature => "Literature",
            Category::Maps => "Maps",
            Category::Math => "Math",
            Category::NumericalAnalysis => "NumericalAnalysis",
            Category::MedicalSoftware => "MedicalSoftware",
            Category::Physics => "Physics",
            Category::Robotics => "Robotics",
            Category::Spirituality => "Spirituality",
            Category::Sports => "Sports",
            Category::ParallelComputing => "ParallelComputing",
            Category::Amusement => "Amusement",
            Category::Archiving => "Archiving",
            Category::Compression => "Compression",
            Category::Electronics => "Electronics",
            Category::Emulator => "Emulator",
            Category::Engineering => "Engineering",
            Category::FileTools => "FileTools",
            Category::FileManager => "FileManager",
            Category::TerminalEmulator => "TerminalEmulator",
            Category::Filesystem => "Filesystem",
            Category::Monitor => "Monitor",
            Category::Security => "Security",
            Category::Accessibility => "Accessibility",
            Category::Calculator => "Calculator",
            Category::Clock => "Clock",
            Category::TextEditor => "TextEditor",
            Category::Documentation => "Documentation",
            Category::Adult => "Adult",
            Category::Core => "Core",
            Category::KDE => "KDE",
            Category::GNOME => "GNOME",
            Category::XFCE => "XFCE",
            Category::GTK => "GTK",
            Category::Qt => "Qt",
            Category::Motif => "Motif",
            Category::Java => "Java",
            Category::ConsoleOnly => "ConsoleOnly",
            Category::Screensaver => "Screensaver",
            Category::TrayIcon => "TrayIcon",
            Category::Applet => "Applet",
            Category::Shell => "Shell",
            Category::Unknown => "",
        }
    }
}
